### ISSUE TITLE
`cargo audit` misreporting alpha version

### ISSUE THREAD

**Issue by jsgf** [RustSec/cargo-audit#116]
Running `cargo audit` reports:
```
ID:      RUSTSEC-2016-0002
Crate:   hyper
Version: 0.13.0-a.0
Date:    2016-05-09
URL:     https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v094-2016-05-09
Title:   HTTPS MitM vulnerability due to lack of hostname verification
Solution: upgrade to: >= 0.9.4

ID:      RUSTSEC-2017-0002
Crate:   hyper
Version: 0.13.0-a.0
Date:    2017-01-23
URL:     https://github.com/hyperium/hyper/wiki/Security-001
Title:   headers containing newline characters can split messages
Solution: upgrade to: >= 0.10.2 OR < 0.10.0, >= 0.9.18
```

It looks like it's misinterpreting `0.13.0-a.0` as being older than `0.9.4`.

**Comment by tarcieri** [comment]
Which version of `cargo-audit` are you using? I'm guessing you're encountering #30.

If so, please try out v0.9.0-beta1, which has a new version resolver which should address this: https://twitter.com/RustSec/status/1171164271113203713

**Comment by tarcieri** [comment]
Please reopen if this issue persists with `v0.9.0-beta1`
