### ISSUE TITLE
Doesn't seem to be working behind a proxy?

### ISSUE THREAD

**Issue by mkpankov** [RustSec/cargo-audit#152]
Seems to hang indefinitely when running behind a proxy

```
➜  seidhe git:(master) ✗ echo $http_proxy
http://localhost:3128/
➜  seidhe git:(master) ✗ echo $https_proxy
http://localhost:3128/
➜  seidhe git:(master) ✗ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
^C
```

Network monitor show it makes a request directly to the host instead of to the proxy.

**Comment by tarcieri** [comment]
Another relevant issue about this: https://github.com/RustSec/rustsec-crate/issues/94

**Comment by tarcieri** [comment]
Note that, in the interim, you can pull the advisory DB repo yourself via the git CLI and then run `cargo audit -n` or `cargo audit --no-fetch`

**Comment by tarcieri** [comment]
Note: this should be addressed by https://github.com/RustSec/rustsec-crate/issues/94 but it needs another release of the `rustsec` crate and cargo-audit

**Comment by tarcieri** [comment]
This should be fixed now
