### ISSUE TITLE
Installation Fail on Alpine Linux

### ISSUE THREAD

**Issue by alimalek71** [RustSec/cargo-audit#158]
I run a docker container from `rust:1.38.0-alpine3.10` image and get an error on installation of `cargo-audit`

```
error: failed to compile `cargo-audit v0.10.0`, intermediate artifacts can be found at `/tmp/cargo-install2YeN7N`

Caused by:
  cannot produce proc-macro for `abscissa_derive v0.4.0` as the target `x86_64-unknown-linux-musl` does not support these crate 
```
How can I fix it?

**Comment by tarcieri** [comment]
Here is the relevant upstream issue:

https://github.com/rust-lang/rust/issues/59302

tl;dr: musl hosts presently don't support dynamic linking, which is needed for proc macros, of which this tool uses several.

The only workaround other than waiting for the above issue to be fixed is to build a binary from a GNU host with a musl `--target`
