### ISSUE TITLE
Fails to build out of the box on macOS

### ISSUE THREAD

**Issue by briansmith** [RustSec/cargo-audit#163]
Build log:
<details>
error: failed to run custom build command for `openssl-sys v0.9.52`

Caused by:
  process didn't exit successfully: `/var/folders/6f/80clx4ds5ps1kfw25c3c0ql80000gn/T/cargo-install24dfBz/release/build/openssl-sys-a97bfcfcd73443d5/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR
X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR
X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_DIR
X86_64_APPLE_DARWIN_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
run pkg_config fail: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: No such file or directory (os error 2)"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-apple-darwin
$TARGET = x86_64-apple-darwin
openssl-sys = 0.9.52

It looks like you're compiling on macOS, where the system contains a version of
OpenSSL 0.9.8. This crate no longer supports OpenSSL 0.9.8.

As a consumer of this crate, you can fix this error by using Homebrew to
install the `openssl` package, or as a maintainer you can use the openssl-sys
0.7 crate for support with OpenSSL 0.9.8.

Unfortunately though the compile cannot continue, so aborting.

', /Users/administrator/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.52/build/find_normal.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-audit v0.10.0`, intermediate artifacts can be found at `/var/folders/6f/80clx4ds5ps1kfw25c3c0ql80000gn/T/cargo-install24dfBz`

Caused by:
  build failed
</details>

In particular, note this part of the output:
> It looks like you're compiling on macOS, where the system contains a version of
OpenSSL 0.9.8. This crate no longer supports OpenSSL 0.9.8.
>
> As a consumer of this crate, you can fix this error by using Homebrew to
install the `openssl` package, or as a maintainer you can use the openssl-sys
0.7 crate for support with OpenSSL 0.9.8.

Homebrew shouldn't be a prerequisite for `cargo-audit`. And, really, neither should OpenSSL.

**Comment by tarcieri** [comment]
OpenSSL is a transitive dependency via the `git2` crate, which uses it to fetch https://github.com/rustsec/advisory-db over HTTPS, much in the same way Cargo fetches the crates.io index.

> Homebrew shouldn't be a prerequisite for `cargo-audit`

It appears there's a `vendored-openssl` feature for the `git2` crate, which I assume is how Cargo is solving this problem.

>  And, really, neither should OpenSSL.

The only alternative I can think of:

- using the `git` CLI rather than the `git2` crate, which would help address some other issues (#152)
- a Rust `git` crate which can use e.g. rustls

**Comment by briansmith** [comment]
> > Homebrew shouldn't be a prerequisite for `cargo-audit`
> 
> It appears there's a `vendored-openssl` feature for the `git2` crate, which I assume is how Cargo is solving this problem.

I agree that using that feature would be better than requiring homebrew, from what I understand.

**Comment by briansmith** [comment]
> The only alternatives I can think of:
> 
> * using the `git` CLI rather than the `git2` crate, which would help address some other issues (#152)
> * a Rust `git` crate which can use e.g. rustls

Maybe `git` isn't necessary to fetch the advisory database? Maybe a normal HTTP request to an archive of the repo (maybe GitHub generates these automatically?) would work. Then dependencies should be greatly reduced too.

**Comment by tarcieri** [comment]
> Maybe a normal HTTP request to an archive of the repo (maybe GitHub generates these automatically?) would work. Then dependencies should be greatly reduced too.

Previously `reqwest` was used to fetch a unified TOML file containing the advisory database. Switching to `git2` (also done to align with the crates.io index for possible future upstreaming of all of the functionality into Cargo itself) dramatically reduced the number of dependencies:

![deps](https://pbs.twimg.com/media/DiqGO4EV4AArVAU?format=jpg&name=4096x4096)

Perhaps there are alternative lightweight HTTPS clients to consider, but thus far I consider switching to `git2` a net win dependency-wise.

**Comment by tarcieri** [comment]
As of `cargo-audit` v0.11.1, there's now a `vendored-openssl` Cargo feature
