### ISSUE TITLE
Fix display of patched versions

### ISSUE THREAD

**Issue by dbrgn** [RustSec/cargo-audit#18]
For RUSTSEC-2017-0002, the patched version list looks as follows:

    patched_versions = [">= 0.10.2", "< 0.10.0, >= 0.9.18"]

When printed as a warning, it looks like this:

    Solution: upgrade to: >= 0.10.2, < 0.10.0, >= 0.9.18

It's not clear anymore where a specifier ends, since the specifiers themselves can also contain commas.

Maybe we could separate the specifiers with the word "or" instead?

**Comment by tarcieri** [comment]
How about:

```
Solution: upgrade to:
 - >= 0.10.2
 - < 0.10.0, >= 0.9.18
````

or

```
Solution: upgrade to:
        >= 0.10.2
        < 0.10.0, >= 0.9.18
````

**Comment by dbrgn** [comment]
Of those two I'd prefer the first version.

Or maybe

    Solution: upgrade to >= 0.10.2 or < 0.10.0, >= 0.9.18
