### ISSUE TITLE
Unused patches cause cargo audit to bail with a toml error

### ISSUE THREAD

**Issue by richardwhiuk** [RustSec/cargo-audit#187]
With Cargo Audit 0.10.0, having an unused patch in the Cargo.lock file - e.g.

```
[[patch.unused]]
name = "shiplift"
version = "0.6.0"
source = "git+https://github.com/softprops/shiplift#4c76501fbe640f9ef91feedcd0897518bfd08f68"
```

causes

```
. >  cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 69 security advisories (from /opt/rust/advisory-db)
error: Couldn't load Cargo.lock: parse error: parse error: unknown field `patch`, expected `package` or `metadata` at line 2767 column 1
```

I think Cargo Audit should probably present a warning or error here, but it would be nicer if it didn't bail entirely.

**Comment by tarcieri** [comment]
Thanks for the report! It should probably be filed against the `cargo-lock` crate (which, as it were, I'm working on now):

https://github.com/RustSec/cargo-lock

**Comment by richardwhiuk** [comment]
Ok - I can go ahead and re-raise it there?

**Comment by richardwhiuk** [comment]
Hmm, cargo-audit doesn't appear to use cargo-lock - is that new?

**Comment by richardwhiuk** [comment]
I've raised https://github.com/RustSec/cargo-lock/issues/30

**Comment by tarcieri** [comment]
Thanks!
