### ISSUE TITLE
0.13.1 -D parse error: breaking change?

### ISSUE THREAD

**Issue by kellerkindt** [RustSec/cargo-audit#280]
![grafik](https://user-images.githubusercontent.com/1133787/97339120-7b658d00-1882-11eb-9659-0cd896e4d9d5.png)

![grafik](https://user-images.githubusercontent.com/1133787/97339026-5a04a100-1882-11eb-9623-9d709ef68341.png)

See, this is what happens if you do not pin your dependency versions ... (talking to myself)

**Comment by kellerkindt** [comment]
Well, I was caught off guard #278

**Comment by tarcieri** [comment]
I actually changed `--deny-warnings` specifically to continue to work as-is sans argument in #278 to make this change slightly less disruptive. That now prints a deprecation warning and tells you to use `--deny warnings`.

For `-D`, I wanted to better align with `RUSTFLAGS` and accept similar arguments. `-D` is now short for the new `--deny` option and takes an argument. The same `-D warnings` you'd use with RUSTFLAGS now works with `cargo audit`.

Pardon our dust.

**Comment by kellerkindt** [comment]
Well, all in all the change is reasonable.

**Comment by bmc-msft** [comment]
It would be extremely valuable to declare how you intend to manage versions.   This breaking change came in 0.13.1.

One of many common practices that would prevent surprises like this in the future would be to use [semantic versioning](https://semver.org/spec/v2.0.0.html).

**Comment by tarcieri** [comment]
@bmc-msft this project uses semantic versioning, even if it isn't declared as such.

v0.13.0 was pulled.

As I [just mentioned above](https://github.com/RustSec/cargo-audit/issues/280#issuecomment-717409307), this change was introduced in v0.13.1 to make it slightly less disruptive.

**Comment by bmc-msft** [comment]
It's useful that you're intending to use semantic versioning.  

I saw the release of 0.13.0 when it was first published, looked through the changelog and code and did not see anything that would break our usage. 

The follow-on release of 0.13.1 that introduced a breaking change was what caught me off-guard.

**Comment by tarcieri** [comment]
#206 was a breaking change. It looks like it was not properly noted in the changelog.
