### ISSUE TITLE
Pulling in multiple versions of several dependencies

### ISSUE THREAD

**Issue by branan** [RustSec/cargo-audit#29]
* Two different versions of proc-macro2 (0.4.9, 0.3.8)
* Two different versions of unicode-xid (0.1.0, 0.0.4)
* Two different versions of winapi (0.3.5 and 0.2.8)
* Three different versions of syn (0.13.11, 0.14.5, 0.11.11)
* Three different versions of quote (0.6.4, 0.5.2, 0.3.15)

While rust handles this fine, it does mean that the download and build times for a `cargo install` are a bit more bloated than they need to be

**Comment by tarcieri** [comment]
Yeah 😢 

https://www.reddit.com/r/rustjerk/comments/8o28u1/rust_for_me_lately_feels_like_it_has_too_many_syns/

I think `gumdrop_derive` needs to be updated:

https://github.com/murarth/gumdrop/blob/master/gumdrop_derive/Cargo.toml

**Comment by branan** [comment]
Yeah, procedural macros are definitely still a fast-moving part of the ecosystem. I wasn't sure if there was an easy win in terms of updating your direct dependencies. Having run `cargo tree` myself now, I can see that you're pretty much dependent on other crates to get themselves updated:

* `gumdrop` is indeed be responsible for `syn 0.13.11`, `quote 0.5.2`, and `proc-macro2 0.3.8`.
* `failure` is the one responsible for `quote 0.3.15`, `syn 0.11.11`, and unicode-xid `0.0.4`. It looks like a PR to update those has landed, but a 0.1.2 release hasn't been cut yet.

It also looks like `term 0.4` is based on an older version of the `winapi` ecosystem, pulling in `kernel32-sys` and `winapi 0.2.8`. It looks like `term` has released a 0.5 series that is updated to the newer `winapi` family, and appears to be a clean update for this crate. I've opened a PR at #31. I missed this originally since I was basing my analysis on the output of `cargo install` on a Linux machine.

**Comment by tarcieri** [comment]
@branan thanks for looking into this!

**Comment by tarcieri** [comment]
This should be addressed now
