### ISSUE TITLE
`depentry tree:` has trailing space

### ISSUE THREAD

**Issue by chenrui333** [RustSec/cargo-audit#293]
👋  it looks like the current `cargo-audit` has trailing space for ` Dependency tree:` line
![image](https://user-images.githubusercontent.com/1580956/103158903-02ef4f80-4791-11eb-8ba7-80b270d64b4e.png)

**Comment by Owez** [comment]
@tarcieri I think this should be closed?

**Comment by tarcieri** [comment]
Yeah, it will be fixed the next time we update Abscissa
