### ISSUE TITLE
Cargo-audit shouldn't require .git to be present to proceed with an advisory db

### ISSUE THREAD

**Issue by Firstyear** [RustSec/cargo-audit#313]
Hi there,

I'm currently working on rust packaging for opensuse. To help support this we want to be able to run cargo-audit in our packaging and build services to ensure that vulnerabilities in vendored applications are not present and are able to be detected and responded to.

To do this in our server side infrastructure, we need to package both cargo-audit and the cargo-audit-advisory-db so that we can have fenced offline builders. This also means that we must package both cargo-audit and the advisory-db to distribute to these build hosts.

During the build process, our source management system is removing the .git folder of the advisory-db. This means that the when the advisory-db is installed, there are no .git artefacts.

In this situation, cargo-audit fails to run with the following error:

```
error: couldn't open advisory database: git operation failed: could not find repository from '/usr/share/cargo-audit-advisory-db'; class=Repository (6); code=NotFound (-3)
```

I think that in this situation to assist us with packaging and for offline builds, in a situation where .git is not present then it would be safe to assume:

* That the db may be stale
* And that we must use the --stale flag in tooling that consumes this database when directed

Being able to run without a .git present would really help with this, and being able to use cargo-audit for our builders will support our package security teams in verification of our rust sources (and of course, that we should report issues to rustsec so that we can all benefit).

For now, I am able to work around by manually adding the .git into the sources, but it would be great if I didn't need to do this! 

Thanks,

PS: We aren't going to "force" the use of the packaged advisory-db, by default the packaged cargo-audit will consume the db from .cargo as upstream intends. It's only when we use this within some internally tooling that we required the packaged advisory-db.

**Comment by Firstyear** [comment]
As a followup, in the case the .git isn't present, it should not attempt to be updated either :) But I think that's implied in this situation.

**Comment by tarcieri** [comment]
The fix for this should be pretty straightforward, although `cargo-audit` should probably get bumped to `rustsec` crate v0.23.0 first.

The change needs to happen here:

https://github.com/RustSec/cargo-audit/blob/5dd7f3b/src/auditor.rs#L47-L71

In the event `config.database.fetch` is false, it should use `rustsec::Database::open` rather than `rustsec::Database::load_from_repo`:

https://docs.rs/rustsec/0.23.0/rustsec/database/struct.Database.html#method.open

**Comment by Firstyear** [comment]
No problem mate, I could probably do that PR. Would you like me to wait until v.0.23.0 is updated first? Or should I just submit this now? It looks like v0.22.0 supports the open vs load_from_repo distinction, so I would expect it won't conflict either way.

**Comment by alex** [comment]
Thanks for working on Rust in OpenSUSE!
