### ISSUE TITLE
Upgrading to 0.14.0 with existing local advisory-db causes git fetch error

### ISSUE THREAD

**Issue by tommilligan** [RustSec/cargo-audit#331]
Just upgraded to v0.14.0 of cargo audit locally using:

```bash
cargo install cargo-audit -f
```

Subsequently, auditing a crate fails with an underlying git error:

```bash
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: reference 'refs/heads/main' not found; class=Reference (4); code=NotFound (-3)
```

This was resolved by clearing out my local copy of the advisory db with:

```bash
rm -rf ~/.cargo/advisory-db
```

---

I'm guessing you recently renamed `master` -> `main`? I don't think this needs a technical fix, maybe just a clarifying note in the changelog.

**Comment by tarcieri** [comment]
I added automated support for renaming the local branch in https://github.com/RustSec/rustsec-crate/pull/309 which is now released as `rustsec` v0.23.3. This should prevent the error from occurring for anyone who installs `cargo-audit` going forward.

**Comment by tommilligan** [comment]
That looks perfect - thanks for the quick fix!

**Comment by kpcyrd** [comment]
hey!

this still doesn't work for me for some reason:
```
% cargo audit 
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: reference 'refs/heads/main' not found; class=Reference (4); code=NotFound (-3)
```

Any chance the rust code is specifically looking for a `main` branch that doesn't exist on my repo yet?

**Comment by tarcieri** [comment]
Possibly. It'd need to be some sort of weird state this change didn't handle: https://github.com/RustSec/rustsec-crate/pull/309

...or perhaps you need to forcibly reinstall `cargo-audit` to pick up that change, or reclone your local advisory DB repo?

**Comment by kpcyrd** [comment]
cargo-audit has been installed with pacman (the package currently in `[community-testing]`), cargo-audit works if I rename the cloned advisory repo (`mv ~/.cargo/advisory-db{,.bak}`) but preferably no manual steps would be necessary for the user. :)

**Comment by tarcieri** [comment]
https://github.com/RustSec/rustsec-crate/pull/309 was supposed to address it, so I'm not sure if you have a build that didn't incorporate it or if your local repo was in some strange state

**Comment by freswa** [comment]
It seems to me, that commit 0bcf4d49258e1a469c2035a750494cce7f3d168a, which bumped the version, isn't included in 0.14.0, is it?

**Comment by tarcieri** [comment]
`cargo-audit` v0.14.0 depends on `rustsec` ^v0.23.

Reinstallation should get the latest version of the dependency unless it's installed with `--locked`.

I could cut a point release which would ensure that it wasn't possible to build with the older version, however.

**Comment by freswa** [comment]
That would be much appreciated :)

**Comment by tarcieri** [comment]
Okay. It feels a little silly doing a release with no changes except to `Cargo.lock`, but if people are really having problems because they aren't following the instructions to reinstall then perhaps it will help narrow the problem down.

**Comment by kpcyrd** [comment]
A lot of distros build with `--locked` for reproducible builds, so doing a release that simply updates `Cargo.lock` is perfectly reasonable. :)

I'd even encourage this to ensure bug fixes and security updates in dependencies are shipped to users.

**Comment by tarcieri** [comment]
0.14.1 release here: https://github.com/RustSec/cargo-audit/pull/342

**Comment by flipchan** [comment]
Having the same problem here @tarcieri :
```rust 
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`   
error: couldn't fetch advisory database: git operation failed: reference 'refs/heads
/master' not found; class=Reference (4); code=NotFound (-3)                        

```
