### ISSUE TITLE
cargo-audit missing vulnerability

### ISSUE THREAD

**Issue by desandy** [RustSec/cargo-audit#346]
Hello,

I am new to using this, however, I have a project with a vulnerability, or so I think, and yet cargo-audit does not output it in it's list.

An excerpt from the Cargo.lock file:

[[package]]
name = "rand_core"
version = "0.4.2"
source = "registry+https://github.com/rust-lang/crates.io-index"

This appears to be fall into this vulnerability:

**https://rustsec.org/advisories/RUSTSEC-2021-0023.html**

Summary: rand_core::le::read_u32_into and read_u64_into have incorrect checks on the source buffer length, allowing the destination buffer to be under-filled.

Implications: some downstream RNGs, including Hc128Rng (but not the more widely used ChaCha*Rng), allow seeding using the SeedableRng::from_seed trait-function with too short keys.

More Info
https://github.com/rust-random/rand/pull/1096

**Patched Versions
>=0.6.2**

I am running cargo-audit version 0.14.1 and Rust 1.50.0.

What am I missing here?

Thank you in advance for what is probably a stupid question.

**Comment by alex** [comment]
Looking at the raw report: https://github.com/RustSec/advisory-db/blob/main/crates/rand_core/RUSTSEC-2021-0023.md

We can see that versions < 0.6 are not impacted.

**Comment by alex** [comment]
I'm going to close this as a dupe of https://github.com/RustSec/advisory-db/issues/879, which is about getting this info on the website.

**Comment by desandy** [comment]
So, why does the Rust advisory show patched version >=0.6.2?

**Comment by desandy** [comment]
Okay.  I understand.  Thank you!
