### ISSUE TITLE
Identifying the immediate dependencies with vulnerable transitive dependencies

### ISSUE THREAD

**Issue by colindean** [RustSec/cargo-audit#39]
I've got `cargo audit` running as a part of my master build process. When it has a result, obviously the build stops and the build output contains the audit output.

All of the problems that it's identified thus far have been vulnerabilities in transitive dependencies, i.e. our dependencies' dependencies. In order to _find_ the immediate dependency, we have to look through Cargo.lock or run `cargo tree` (after installing it with `cargo install cargo-tree`) for the out of date dependency.

I'm investigating automating this investigation in some way.

My first thought is to capture the output of `cargo audit`, parse each report, and then highlight in the output of `cargo tree` each vulnerable dependency.

Alternatively, there's a way to show the inverted dependency tree: `cargo tree -i -p <package>:<version>`. I could probably parse the output of `cargo audit` to get each crate and its version, then output the tree like so.

I think what I'm getting at is that it would be neat if `cargo-audit` just _told_ me the immediate dependency.

**Comment by tarcieri** [comment]
> I think what I'm getting at is that it would be neat if cargo-audit just told me the immediate dependency.

The information needed to determine this is in `Cargo.lock`. We'd need to parse the dependency tree, and find the dependency pulling in a vulnerable crate, then highlight that in each vulnerability report.

**Comment by colindean** [comment]
Here's what I'm thinking:

* `Cargo.lock` itself does not denote which packages are the immediate dependencies. We _can_ get that information from `Cargo.toml`, though.
* `audit()` in `src/main.rs` gets to a state where it knows the vulnerable crates in the dependency tree, but it doesn't know _where_ in the tree they are.
* The app can load the immediate dependencies from `Cargo.toml` and find them in the `Lockfile`'s `packages`, a `Vec<Package>`. It then starts a recursive search, looking at each `Package`'s `dependencies` until it finds the affected package.

It doesn't look like `rustsec-crate`'s `Package` has a way to parse a package out of its dependencies, in order to compare the `PackageName` and `Version` using the derived `Eq`. That probably needs to happen.

There's a [`cargo_toml` crate](https://crates.io/crates/cargo_toml) which looks like it might facilitate parsing `Cargo.toml`. We can get dependent crate names easily, but I think we'll hit a problem with matching on _version_ since the `Cargo.toml` version _could_ be a constrained version. That's where I get confused.

It might help to go see what `cargo-tree` does when you invert the tree.

**Comment by tarcieri** [comment]
cargo-audit v0.9.0(-beta1) includes a feature which does this, similar to `cargo-tree`:

https://twitter.com/RustSec/status/1171164271113203713

![image](https://user-images.githubusercontent.com/797/64574942-44eb4c80-d326-11e9-83d3-e4dfb4f4d549.png)

It builds an inverse dependency graph from `Cargo.lock` using the `petgraph` crate, which is the same one `cargo-tree` uses.

With that, I'd consider this addressed.
