### ISSUE TITLE
Hard to find which dependency is pulling in an insecure crate

### ISSUE THREAD

**Issue by dvdplm** [RustSec/cargo-audit#47]
(or, possibly, there's a bug in `cargo audit` that reports spurious dependencies)

We have a case where `cargo audit` is signalling an insecure dependency on `smallvec 0.5.1` but there is no crate that use it and it does not appear in `Cargo.lock` or in the `cargo tree` output. What's a good strategy to debug this?

To repeat:
- check out https://github.com/paritytech/parity-ethereum/pulls
- run `cargo audit`
- notice two versions of the `smallvec` crate are reported: 0.2.1 and 0.5.1
- notice `smallvec 0.5.1` does not appear in `Cargo.lock`
- notice `cargo tree` does not mention `smallvec 0.5.1` anywhere

**Comment by zofrex** [comment]
The latest version of that repo, at the time of writing `e7f1204`, doesn't have any vulnerabilities in its dependencies according to cargo audit (congratulations!)

For reproducing purposes, the newest commit on the master branch that does is `b8da38f4e`. However, I can't reproduce the reported issue. Here's the output of `cargo audit`:

```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 14 security advisories (from /Users/zofrex/.cargo/advisory-db)
    Scanning Cargo.lock for vulnerabilities (377 crate dependencies)
error: Vulnerable crates found!

ID:	 RUSTSEC-2018-0003
Crate:	 smallvec
Version: 0.2.1
Date:	 2018-07-19
URL:	 https://github.com/servo/rust-smallvec/issues/96
Title:	 Possible double free during unwinding in SmallVec::insert_many
Solution: upgrade to: >= 0.6.3 OR ^0.3.4 OR ^0.4.5 OR ^0.5.1

ID:	 RUSTSEC-2018-0001
Crate:	 untrusted
Version: 0.5.1
Date:	 2018-06-21
URL:	 https://github.com/briansmith/untrusted/pull/20
Title:	 An integer underflow could lead to panic
Solution: upgrade to: >= 0.6.2

error: 2 vulnerabilities found!
```

There is only one instance of `smallvec` reported, although I note that `untrusted` is reported at version "0.5.1" which seems unlikely to be a coincidence.

If there was a bug in `cargo audit` that produced different output 23 days ago, it appears to be fixed. I did try a random commit from ~1 month ago and couldn't reproduce the issue there, either.

I suspect this can be closed, unless @dvdplm is still seeing this?

**Comment by dvdplm** [comment]
> There is only one instance of `smallvec` reported, although I note that `untrusted` is reported at version "0.5.1" which seems unlikely to be a coincidence.

Not sure I understand what you mean here. Can you elaborate?

**Comment by tarcieri** [comment]
I can't reproduce this issue with cargo-audit v0.5.2, which is the latest release:

```
$ cargo audit --version
cargo-audit 0.5.2
$ git clone https://github.com/paritytech/parity-ethereum/
Cloning into 'parity-ethereum'...
remote: Enumerating objects: 110, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 139314 (delta 40), reused 42 (delta 21), pack-reused 139204
Receiving objects: 100% (139314/139314), 56.91 MiB | 34.89 MiB/s, done.
Resolving deltas: 100% (100123/100123), done.
$ cd parity-ethereum
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 14 security advisories (from /Users/bascule/.cargo/advisory-db)
    Scanning Cargo.lock for vulnerabilities (388 crate dependencies)
     Success No vulnerable packages found
```

**Comment by dvdplm** [comment]
> @dvdplm can you still reproduce this?

No, seems fixed! Closing. :)
