### ISSUE TITLE
Add an --ignore option

### ISSUE THREAD

**Issue by tarcieri** [RustSec/cargo-audit#53]
Currently RustSec advisories are only as fine grained as individual crates, however there are circumstances where an advisory is not applicable, e.g. it requires a certain cargo feature to be enabled, or affects an API which a project isn't using.

While it would be nice to make advisories more fine-grained and apply to specific cargo features, or integrate with tools like `cargo-geiger` to only show advisories that actually impact a particular project, in absence of such features `cargo-audit` users presently have no mechanism to opt out of advisories which do not apply.

The carrot-and-stick answer would be for them to simply upgrade regardless, however I think adding an `--ignore` option might be a good stopgap, e.g.:

```
$ cargo audit --ignore RUSTSEC-2017-0001
```

This would allow the project to pass an audit despite having a known vulnerability.

While I see downsides to this approach, the bigger worry I'd have is losing `cargo-audit` users because of false positives and the absence of workarounds or finer-grained auditing features.

Any objections or alternatives people have in mind?

**Comment by jsirois** [comment]
@tarcieri I took a whack at this since we'll need to do something like `--ignore` over in https://github.com/pantsbuild/pants to avoid either hosting our own advisory-db or else filtering our Cargo.lock before handing off for audit.
