### ISSUE TITLE
Shall crev's negative reviews automatically get into cargo-audit database?

### ISSUE THREAD

**Issue by vi** [RustSec/cargo-audit#68]
[`cargo crev`][1] is a distributed code review tool. It has `rating: dangerous` outcome, and such reviews may be in scope for cargo audit.

[1]:https://github.com/dpc/crev

**Comment by tarcieri** [comment]
See also https://github.com/RustSec/advisory-db/issues/85

**Comment by tarcieri** [comment]
I'd suggest continuing this on https://github.com/RustSec/advisory-db/issues/85
