### ISSUE TITLE
Failing to report recent smallvec advisory

### ISSUE THREAD

**Issue by rfk** [RustSec/cargo-audit#78]
I noticed that `cargo audit` does not report the recent [smallvec advisory](https://github.com/RustSec/advisory-db/pull/119) for my project:

```
$ grep "smallvec 0.6.9" Cargo.lock 
 "smallvec 0.6.9 (registry+https://github.com/rust-lang/crates.io-index)", 
 "smallvec 0.6.9 (registry+https://github.com/rust-lang/crates.io-index)", 
"checksum smallvec 0.6.9 (registry+https://github.com/rust-lang/crates.io-index)" = "c4488ae950c49d403731982257768f48fada354a5203fe81f9bb6f43ca9002be"
$ 
$ ls ~/.cargo/advisory-db/crates/smallvec/
RUSTSEC-0000-0000.toml  RUSTSEC-2018-0003.toml
$ 
$ cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 29 security advisories (from /home/rfk/.cargo/advisory-db)
Scanning Cargo.lock for vulnerabilities (301 crate dependencies)
Success No vulnerable packages found
$ 
```

I think it's failing to load the file named `RUSTSEC-0000-0000.toml`. Manually modifying my copy of the advisory db to rename that file to `RUSTSEC-2019-0009.toml` causes `cargo audit` to successfully detect the advisory.

Is this an issue with `cargo-audit` that it should handle such filenames, or does the file in the advisory db need to be renamed with a unique id?

**Comment by tarcieri** [comment]
I've been very busy today and merged it but never assigned it a RUSTSEC ID (Travis CI being horribly backlogged hasn't been helping).

I'll try to do it later tonight.

**Comment by rfk** [comment]
OK thanks, that makes sense - I guess it's in a kind of "pending" state until it gets an ID assigned?

I'll go ahead and close this since it's not an issue in `cargo-audit`; thanks for all your work on this project!

**Comment by tarcieri** [comment]
Assigned RUSTSEC-2019-0009 in https://github.com/RustSec/advisory-db/issues/120

See also the related issue on automating ID assignment which might've helped here: https://github.com/RustSec/advisory-db/issues/111
