### ISSUE TITLE
RUSTSEC-2019-0011 advisory version info does not match `cargo audit` guidance when run

### ISSUE THREAD

**Issue by scooter-dangle** [RustSec/cargo-audit#88]
(Apologies if this is the wrong place to post this. Happy to close/re-post elsewhere if appropriate.)

In a project that transitively depends on [`memoffset`](https://crates.io/crates/memoffset) (with version `0.2.1` in `Cargo.lock`), running `cargo-audit 0.7.0` gives

```
error: Vulnerable crates found!

ID:      RUSTSEC-2019-0011
Crate:   memoffset
Version: 0.2.1
Date:    2019-07-16
URL:     https://github.com/Gilnaa/memoffset/issues/9#issuecomment-505461490
Title:   Flaw in offset_of and span_of causes SIGILL, drops uninitialized memory of arbitrary type on panic in client code
Solution: upgrade to: >= 0.5.0

error: 1 vulnerability found!
```

But at https://rustsec.org/advisories/RUSTSEC-2019-0011.html, `< 0.3.0` is listed under `Unaffected Versions`.

**Comment by tarcieri** [comment]
What version of `cargo-audit` are you using? My guess is < v0.6, in which case you are likely encountering this bug: https://github.com/RustSec/rustsec-crate/pull/53

**Comment by scooter-dangle** [comment]
> What version of `cargo-audit` are you using? My guess is < v0.6, in which case you are likely encountering this bug: [RustSec/rustsec-crate#53](https://github.com/RustSec/rustsec-crate/pull/53)

`0.7.0`

**Comment by Shnatsel** [comment]
We forgot to update the website. The advisory was extended to all versions below 0.5.0 in a subsequent PR: https://github.com/RustSec/advisory-db/pull/129

**Comment by tarcieri** [comment]
Ugh, so that’s it. Will update the web site when I get back

**Comment by tarcieri** [comment]
Web site has been updated. Closing this issue.
