### ISSUE TITLE
Add pre-built binaries to Github releases

### ISSUE THREAD

**Issue by Jake-Shadle** [RustSec/cargo-audit#90]
First of all, thanks for cargo-audit, we've just now caught our first issue with it!

One thing that would nice would be to have pre built binaries for each Github release that can be downloaded, decompressed, and copied somewhere into PATH without having to run cargo install, similar to [sccache](https://github.com/mozilla/sccache/releases) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny/releases). This would make both building CI images as well as adhoc downloading + running in CI faster (though less easily).

**Comment by tarcieri** [comment]
See #66

**Comment by Jake-Shadle** [comment]
Ahh apologies, I did a quick search to see if there was an existing issue for this but failed hard anyways.

**Comment by tarcieri** [comment]
Haha, I was going to offer to leave this open to re-evaluate it, as it's been awhile.

**Comment by Jake-Shadle** [comment]
Hmm, well it's up to you, I was going to just add a comment to that existing issue. :slightly_smiling_face:
