### ISSUE TITLE
skip database fetching option

### ISSUE THREAD

**Issue by dubbl** [RustSec/cargo-audit#93]
I would like to use `cargo audit` in our CI pipeline. But we have a "no internet-dependencies" policy in our build process, so I'd like to download the db on a regular basis outside the build process and then just check the .toml files against the already downloaded db at build time.

As I see it `cargo audit` has two major functions, 1. downloading the db and 2. checking the dependencies against it.

How about a flag `download-db` or `update-db` that defaults to true? I'd be happy to make a PR for it, if there is a consensus that it would be useful.

**Comment by tarcieri** [comment]
@dubbl sure, we'd accept a PR for this feature

**Comment by dubbl** [comment]
Ooh, I was working on this and was looking into a unit test - but your version with the matching seems more rust-esque anyway, I was splitting up downloading and loading of the repo. 

- I guess with the --no-fetch option the "--stale" option doesn't is implied. If we expose a stale-check in the advisory database client we could check it anyway, even if no new database was fetched.

**Comment by tarcieri** [comment]
@dubbl if you'd like to contribute a test you could try adding an acceptance test:

https://github.com/RustSec/cargo-audit/blob/master/tests/acceptance.rs

Re: `--stale`, I think it's probably a good thing it isn't implied - if you're relying on an external mechanism to source the git repo, it's possible that may go stale, in which case I think it's better to alert for that by default.
